services:
    app:
        image: oven/bun:1
        container_name: API-BUN
        working_dir: /app
        ports:
            - "3000:3000"
        volumes:
            - .:/app
        env_file:
            - env/.env.dev
        command: >
            sh -c "sleep 10 && bun install && bunx prisma migrate dev && bunx prisma generate && bun --watch src/app.ts"
        depends_on:
            - mysql
    mysql:
        image: mysql:8
        container_name: BddMysql
        env_file:
            - env/.env.dev
        volumes:
            - ./env/sql/initUser.sql:/docker-entrypoint-initdb.d/init.sql
            - mysqldata:/var/lib/mysql
        ports:
            - "3306:3306"
    phpmyadmin:
        image: phpmyadmin:5
        container_name: myAdmin
        ports:
            - "8080:80"
        env_file:
            - env/.env.dev
        depends_on:
            - mysql
volumes:
    mysqldata:
