services:
    app:
        image: oven/bun:1
        container_name: API-BUN
        working_dir: /app
        ports:
            - "3000:3000"
        volumes:
            - .:/app
        environment:
            - PORT=3000
            - DATABASE_URL=mysql://root:root@mysql:3306/mydb
        command: >
            sh -c "sleep 3 && bun install && bunx prisma migrate deploy && bunx prisma generate && bun --watch src/app.ts"
        depends_on:
            - mysql

    mysql:
        image: mysql:8
        container_name: BddMysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=mydb
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - "3306:3306"
    phpmyadmin:
        image: phpmyadmin:5
        container_name: myAdmin
        ports:
            - "8080:80"
        environment:
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=root
        depends_on:
            - mysql

volumes:
    mysqldata:
